name: Validate build

on:
  push:
    branches:
      - main

jobs:
  validate-build-windows:
    runs-on: windows-latest
    timeout-minutes: 3
    steps:
      - name: Setup Odin
        uses: laytan/setup-odin@v2.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Build Rune
        run: |
          .\scripts\build.bat
      - name: Run tests
        run: |
          .\bin\rune.exe test

  validate-build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Setup Odin
        uses: laytan/setup-odin@v2.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Make build script executable
        run: chmod +x ./scripts/build.sh
      - name: Build Rune
        run: |
          ./scripts/build.sh
      - name: Run tests
        run: |
          ./bin/rune test test_linux

  validate-build-macos:
    runs-on: macos-latest
    timeout-minutes: 3
    steps:
      - name: Setup Odin
        uses: laytan/setup-odin@v2.9.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
      - name: Make build script executable
        run: chmod +x ./scripts/build.sh
      - name: Build Rune
        run: |
          ./scripts/build.sh
      - name: Run tests
        run: |
          ./bin/rune test test_macos